Editing posts comments profile
dr-lilith/my-first-blog pull request #15
Opened 2022-07-05 11:42 UTC by dr-lilith

Editing posts, comments, profile done + searching posts by title.

2022-07-05 12:09 UTC, MaximShidlovski23 requested changes

2022-07-05 12:09 UTC, MaximShidlovski23 commented on frontend/front/src/components/UserProfile/MyPosts/MyPostsContainer.js
> +  //const navigate = useNavigate();
remove comments

2022-07-05 12:27 UTC, dr-lilith commented on frontend/front/src/components/UserProfile/MyPosts/MyPostsContainer.js
> +  //const navigate = useNavigate();
done

2022-07-06 06:46 UTC, MaximShidlovski23 approved these changes

2022-07-06 11:14 UTC, merged