Implemented reaction storage.
dr-lilith/my-first-blog pull request #3
Opened 2022-05-30 16:02 UTC by dr-lilith

Prepared base for rating calculation. Still considering the right implementation approach.

2022-06-01 04:49 UTC, MaximShidlovski23 requested changes

2022-06-01 08:36 UTC, dr-lilith commented on posts/models.py
> +    post = models.ForeignKey(Post, on_delete=models.CASCADE)
This model is to track personal user reaction to a certain post (like or dislike). Overall rating of the post is calculated dinamically based on reaction table.

2022-06-03 07:14 UTC, MaximShidlovski23 requested changes

2022-06-03 07:14 UTC, MaximShidlovski23 commented on posts/views.py
>  def count_likes(request, id):
These endpoints do not make sense, and why make 2 separate endpoints for the count of likes and dislikes, if you can make one that will return both

2022-06-03 07:16 UTC, MaximShidlovski23 approved these changes

2022-06-03 07:16 UTC, MaximShidlovski23 approved these changes

2022-06-03 09:39 UTC, merged